GET http://localhost:3500/api/estudiantes

###
POST http://localhost:3500/api/estudiantes
Content-Type: application/json

{
    "nombre":"Nombre 02",
    "correo":"nombre02@email.com"
}

###
GET http://localhost:3500/

###
PUT http://localhost:3500/api/estudiantes/111

###
DELETE http://localhost:3500/api/estudiantes/222
