GET http://localhost:3500/api/estudiantes

###
POST http://localhost:3500/api/estudiantes
Content-Type: application/json

{
    "nombre":"Nombre 03",
    "correo":"nombre03@email.com"
}

###
GET http://localhost:3500/

###
PUT http://localhost:3500/api/estudiantes/6147f55dd44df7f7a0bb465e
Content-Type: application/json

{
    "nombre":"Nombre 33"
}

###
DELETE http://localhost:3500/api/estudiantes/6147f542d44df7f7a0bb465a
