GET http://localhost:3500/api/estudiantes

###
POST http://localhost:3500/api/estudiantes
Content-Type: application/json

{
    "nombre":"Nombre 04",
    "correo":"nombre04@email.com",
    "materias":[
        {
            "nombre":"Mat",
            "nota":88,
            "comentario":"MB"
        },
        {
            "nombre":"Esp",
            "nota":98,
            "comentario":"E"
        }
    ]
}

###
GET http://localhost:3500/

###
PUT http://localhost:3500/api/estudiantes/6147f55dd44df7f7a0bb465e
Content-Type: application/json

{
    "nombre":"Nombre 33"
}

###
DELETE http://localhost:3500/api/estudiantes/6147f542d44df7f7a0bb465a

###
GET http://localhost:3500/api/materias/614805c838d73e8cf8286edd